apiVersion: v1
kind: ReplicationController # 副本控制器RC；kind代表的此资源对象的类型
metadata:
  name: mysql # RC名称，全局唯一
spec:
  replicas: 1 # Pod副本期待数
  selector:
    app: mysql # 符合目标的Pod拥有此标签
  template: # 根据此模板创建Pod的副本（实例）
    metadata:
      labels: # 这里的label必须匹配之前的spec.selector，否则此RC每次创建一个无法匹配Label的Pod，就会不停的尝试创建新的Pod
        app: mysql # Pod副本拥有的标签，对应RC的Selector
    spec:
      containers: # Pod内容器的定义部分
      - name: mysql # 容器的名称
        image: mysql # 容器对应的docker image
        ports:
        - containerPort: 3306 # 容器应用监听的端口号
        env: # 注入容器内的环境变量；可以在容器中通过env命令查询到此变量
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"