version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee:16.11.0-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.8:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '1443:443'
      - '2424:2424'
    volumes:
      - '/dataz/data/gitlab/config:/etc/gitlab'
      - '/dataz/data/gitlab/logs:/var/log/gitlab'
      - '/dataz/data/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'