apiVersion: v1
kind: ReplicationController 
metadata:
  name: debug 
spec:
  replicas: 1 
  selector:
    app: debug
  template:
    metadata:
      labels: 
        app: debug
    spec:
      containers:
      - name: debug
        image: fabuler/debug-ubuntu-16:latest