FROM osrf/ubuntu_i386:trusty

RUN apt-get clean
RUN apt-get update

RUN apt install -y net-tools \
    vim \
    wget \
    git \
    curl \
    telnet \
    build-essential \
    gdb \
    qemu-system-x86