# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |base_config|
    base_config.vm.define "k8s-master" do |config|
        config.vm.box = "ubuntu/xenial64"
        config.vm.network "private_network", ip: "192.168.56.190" # host-only模式
        config.vm.hostname = "k8s-master"
        config.vm.provider "virtualbox" do |vb|
            vb.gui = true # headless模式有问题，无法启动，先用gui模式
            vb.memory = 2048 # master最低配置，https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
            vb.cpus = 2 # master最低配置
        end
        config.vm.provision :shell do |shell|
            shell.path = "master.sh"
        end
    end
end