version: "3.7"
services:

    prometheus:
        image: bitnami/prometheus:2.28.1
        volumes:
            - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
        depends_on: 
            - prometheus-kafka-adapter
    prometheus-kafka-adapter:
        image: telefonica/prometheus-kafka-adapter:1.7.0
        environment:
            - KAFKA_BROKER_LIST=kafka:9092
            - KAFKA_TOPIC=prometheus_metrics
        depends_on: 
            - kafka
    kafka:
        image: bitnami/kafka:2.8.0
        # ports:
        #     - "9092:9092"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    zookeeper:
        image: bitnami/zookeeper:3.7.0
        # ports:
        #     - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kibana:
        image: bitnami/kibana:7.10.2
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
    elasticsearch:
        image: bitnami/elasticsearch:7.10.2
