version: "3.7"
services:
    grafana:
        image: grafana/grafana:master
        ports:
            - 3000:3000
        # volumes:
        #     - ./examples/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
        #     - ./examples/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    prometheus:
        image: bitnami/prometheus:2.28.1
        ports: 
            - 9090:9090
        volumes:
            - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
        depends_on: 
            - prometheus-kafka-adapter
            # - prometheus-influxdb-adapter
    # prometheus-influxdb-adapter: 
    #     image: kaorimatz/prometheus-influxdb-adapter:0.2.0
    #     # ports: 
    #     #     - 9201:9201
    #     environment:
    #         - WRITE_INFLUXDB_URL=http://prometheus:password@influxdb:8086
    #     command: [
    #         "--log.level=debug",
    #         "--read.influxdb.field=max_over_time:max",
    #         "--read.influxdb.field=min_over_time:min",
    #         "--read.influxdb.field=sum_over_time:sum",
    #         "--read.influxdb.field=mean",
    #         "--read.influxdb.retention-policy=1h:1h",
    #         "--read.influxdb.retention-policy=5m:5m",
    #         "--read.influxdb.retention-policy=1m",
    #         "--read.influxdb.rpc-address=influxdb:8088",
    #     ]
    #     depends_on:
    #         - influxdb
    # prometheus-influxdb-adapter:
    #     image: kaorimatz/prometheus-influxdb-adapter:0.2.0
    #     # ports: 
    #     #     - 9201:9201
    #     environment:
    #         - WRITE_INFLUXDB_URL=http://my_user:my_password@influxdb:8086
    #     command: [
    #         "--log.level=debug",
    #         "--read.influxdb.field=max_over_time:max",
    #         "--read.influxdb.field=min_over_time:min",
    #         "--read.influxdb.field=sum_over_time:sum",
    #         "--read.influxdb.field=mean",
    #         "--read.influxdb.retention-policy=1h:1h",
    #         "--read.influxdb.retention-policy=5m:5m",
    #         "--read.influxdb.retention-policy=1m",
    #         "--read.influxdb.rpc-address=influxdb:8082",
    #     ]
    #     depends_on: 
    #         - influxdb
    influxdb:
        image: bitnami/influxdb:1.8.5
        # ports:
        #     - 8082:8082
        #     - 8086:8086
        #     - 8089:8089
        # volumes:
        #     - ./examples/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
        #     - ./examples/influxdb/prometheus.iql:/docker-entrypoint-initdb.d/prometheus.iql:ro
        environment:
            - INFLUXDB_DB=prometheus
            - INFLUXDB_ADMIN_USER_PASSWORD=admin_password
            # - INFLUXDB_ADMIN_USER=admin
            # - INFLUXDB_ADMIN_PASSWORD=password
            - INFLUXDB_USER=my_user
            - INFLUXDB_USER_PASSWORD=my_password
            # - INFLUXDB_READ_USER=grafana
            # - INFLUXDB_READ_USER_PASSWORD=password
    # influxdb:
    #     image: bitnami/influxdb:1.8.5
    #     # ports:
    #     #     - 8082:8082
    #     #     - 8086:8086
    #     #     - 8089:8089
    #     environment: 
    #         - INFLUXDB_ADMIN_USER_PASSWORD=admin_password
    #         - INFLUXDB_USER=my_user
    #         - INFLUXDB_USER_PASSWORD=my_password
    #         - INFLUXDB_DB=prometheus
    prometheus-kafka-adapter:
        image: telefonica/prometheus-kafka-adapter:1.7.0
        environment:
            - KAFKA_BROKER_LIST=kafka:9092
            - KAFKA_TOPIC=prometheus_metrics
        depends_on: 
            - kafka
    logstash_debug:
        image: logstash:7.10.1
        depends_on: 
            - kafka
            - elasticsearch
    logstash:
        image: bitnami/logstash:7.10.2
        environment: 
            - LOGSTASH_CONF_FILENAME=logstash.conf
        volumes: 
            - ./logstash.conf:/bitnami/logstash/config/logstash.conf
        depends_on: 
            - kafka
            - elasticsearch
    kafka:
        image: bitnami/kafka:2.8.0
        # ports:
        #     - "9092:9092"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    zookeeper:
        image: bitnami/zookeeper:3.7.0
        # ports:
        #     - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kibana:
        image: bitnami/kibana:7.10.2
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
    elasticsearch:
        image: bitnami/elasticsearch:7.10.2
        # ports:
        #     - '9200:9200'
        #     - '9300:9300'
